openapi: 3.0.0
servers:
  - url: 'https://example.com:8080'
    description: CloudCerts Connect API
info:
  version: 1.0.0
  title: CloudCerts Connect
  description: CloudCertの発行と発行状況の確認用。
tags:
  - name: 発行プロセス
paths:
  '/certificates/{issuerID}':
    post:
      tags:
        - 発行プロセス
      summary: ブロックチェーン証明書を発行。
      description: |-
        証明書を発行するエンドポイント。
        JSONまたはFormDataのいずれかでリクエストを許可します。
      parameters:
        - name: issuerID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                html_template:
                  type: object
                  description: |
                    各証明書のビジュアルイメージを生成するためのHTMLテンプレート。
                    コンテンツタイプはパラメータの"html_template_type"に依存します。
                  properties:
                    value:
                      type: string
                      example: <h1>Hello it's certificate</h1>
                    type:
                      type: string
                      enum:
                        - string
                        - link
                        - storage
                        - image
                      description: |
                        "html_template"パラメータのコンテンツタイプを定義。
                        - `string`: HTMLコンテンツを文字列として送信する。 例) "\<h1>Some HTML\</h1>"
                        - `link`: HTMLテンプレートのパブリックリンクを送信する。 例) "http://example.com/path/to/index.html"
                        - `storage`: HTMLテンプレートを保存するクラウドストレージの鍵を保存する。 例) "storage/<key-name>"
                        - `image`: HTMLの代わりに画像を送信する。
                        **デフォルト**: `storage`
                certificate_data:
                  type: array
                  description: |
                    各証明書のデータ、一部の個人データ、HTMLテンプレートの変数。
                  items:
                    type: object
                    properties:
                      username:
                        type: string
                        example: Example username 1
                      email:
                        type: string
                        example: example@lastrust.io
                      label:
                        type: string
                        description: CloudCerts Manager上のラベル。
                        example: Diploma 2020
                      console_id:
                        type: string
                        description: CloudCerts Manager上の識別子。
                        example: '12212121'
                      template_data:
                        type: object
                        description: HTMLのビジュアルを変更するための変数で、HTMLテンプレートに依存。
                        additionalProperties:
                          type: string
                save_pdf:
                  type: boolean
                  description: 発行された証明書をPDFでダウンロードしたい場合は、このオプションを設定します。
                  example: true
                chain:
                  type: string
                  description: 発行プロセスに使用されるチェーン。 (bitcoin_regtest|bitcoin_testnet|bitcoin_mainnet|ethereum_ropsten|ethereum_mainnet|mockchain)
                  example: ethereum_ropsten
                group_name:
                  type: string
                  description: 発行プロセスの名前。
                  example: Test group name
                deferred:
                  type: boolean
                  description: |
                    証明書の署名処理を延期するためのフラグ。
                    証明書ビュー（HTML、PDF、QR-code）が作成され、CloudStorageに保存されます。
                    延期された署名プロセスは、1日1回、バッチプロセスとして実行されます。
                  example: true
          multipart/form-data:
            schema:
              type: object
              properties:
                html_template:
                  type: string
                  format: binary
                  description: |
                    各証明書のビジュアルイメージを生成するためのHTMLテンプレート。
                    コンテンツタイプはパラメータ"html_template_type"に依存します。
                  example: 'http://example.com or <h1>Some HTML</h1> or storage/key/foo/bar'
                html_template_type:
                  type: string
                  enum:
                    - string
                    - link
                    - storage
                    - image
                  description: |
                    "html_template"パラメータのコンテンツタイプを定義する。
                    - `string`: HTMLコンテンツを文字列として送信する。 例) "\<h1>Some HTML\</h1>"
                    - `link`: HTMLテンプレートのパブリックリンクを送信する。 例) "http://example.com/path/to/index.html"
                    - `storage`: HTMLテンプレートを保存するクラウドストレージの鍵を保存する。 例) "storage/<key-name>"
                    - `image`: HTMLの代わりに画像を送信する。
                    **デフォルト**: `string`
                certs_data:
                  description: |
                    各証明書のデータには、名簿、一部の個人情報、HTMLテンプレート変数が含まれています。
                    コンテンツタイプは、パラメータ "certs_data_type"に依存します。
                    CSVの構造:
                    [name, pubkey, identity, certificate_title, criteria_narrative, console_id, <html-template-variables>]
                    **HTMLテンプレート変数はパスカルケースです**(camelCaseに似ていますが、最初の文字は大文字です)
                  type: string
                  format: binary
                  example: FormData file or key of cloud storage
                certs_data_type:
                  description: |
                    "certs_data"パラメータのコンテンツタイプを定義します。
                    - `file`: csvファイルを送信する。
                    - `storage`: csvファイルを保存しているクラウドストレージの鍵を送信する。
                    **デフォルト**: `file`
                  type: string
                  enum:
                    - file
                    - storage
                save_pdf:
                  description: 発行された証明書をPDFでダウンロードしたい場合は、このオプションを設定します。
                  type: boolean
                chain:
                  description: 発行プロセスに使用されるチェーンです。 (bitcoin_regtest|bitcoin_testnet|bitcoin_mainnet|ethereum_ropsten|ethereum_mainnet|mockchain)
                  type: string
                  enum:
                    - bitcoin_regtest
                    - bitcoin_testnet
                    - bitcoin_mainnet
                    - ethereum_ropsten
                    - ethereum_mainnet
                    - mockchain
                group_name:
                  description: 発行プロセスの名前
                  type: string
                deferred:
                  description: |
                    証明書の署名処理を延期するためのフラグ。
                    証明書ビュー（HTML、PDF、QR-code）が作成され、CloudStorageに保存されます。
                    延期された署名プロセスは、1日1回、バッチプロセスとして実行されます。
                  type: boolean
      responses:
        '200':
          description: リクエストに成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  issuer_id:
                    type: string
                    format: uuid
                    example: e10687c2-4305-43bd-a355-8bd07d26cc95
                  process_id:
                    type: string
                    format: uuid
                    example: e10687c2-4305-43bd-a355-8bd07d26cc95
  '/issuers/{issuerID}/processes/{processID}':
    get:
      tags:
        - 発行プロセス
      summary: 発行プロセスのステータスを取得。
      parameters:
        - name: issuerID
          in: path
          required: true
          schema:
            type: string
        - name: processID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 発行プロセスのステータス。
          content:
            application/json:
              schema:
                type: object
                properties:
                  issuer_id:
                    type: string
                    format: uuid
                    example: e10687c2-4305-43bd-a355-8bd07d26cc95
                  process_id:
                    type: string
                    format: uuid
                    example: e10687c2-4305-43bd-a355-8bd07d26cc95
                  certificates:
                    type: array
                    items:
                      type: object
                      properties:
                        cert_id:
                          type: string
                          format: uuid
                          example: e10687c2-4305-43bd-a355-8bd07d26cc95
                        status:
                          type: string
                          description: status
                          example: Success
                          enum:
                            - Not issued
                            - Success
                            - Deferred
                            - Failed
                        url:
                          type: string
                          example: 'https://cloudcerts.io/viewer/issuers/<issuerID>/certs/<certID>'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Access token for API
security:
  - Bearer: []
